config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get  '/signup',  to: 'users#new'
  get '/create', to: 'recipes#new'
  get '/index', to: 'recipes#index'
  resources :recipes
  resources :users
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name,  presence: true, length: { minimum: 5 }
  validates :preparation,  presence: true
  validates :content,  presence: true
  validates :ingredients,  presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    has_many :recipes
    
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include ApplicationHelper
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
  
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:search]
      @recipes = current_user.recipes.where("name LIKE :search OR ingredients LIKE :search", search: "%#{params[:search]}%")
    else
      @recipes = current_user.recipes.order(params[:sort])
    end
  end
  
  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :preparation, :desc_image, :content, :prep_time, :cook_time, :ingredients, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to '/recipes'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to '/recipes'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "Recetas"
        if page_title.empty?
        base_title
        else
            "#{base_title} | #{page_title}"
        end
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
     # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse bg-info text-white align-right">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <div class="container">
    
    <!---<nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'recipes', recipes_path %></li>
              <li><%= link_to 'New Recipe', new_recipe_path %></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>-->
    
     <% if logged_in? %>
                <nav class="navbar navbar-expand-md navbar-info bg-info text-white shadow-sm align-right">
                    <div class="container">
                        <a class="navbar-brand bg-info text-white rounded" href="/recipes" >
                           Recipes
                        </a>
        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <!-- Left Side Of Navbar -->
                            <ul class="navbar-nav mr-auto">
                                    <li class="nav-item">
                                        <a class="nav-link bg-info text-white rounded" href="/create">New Recipe</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link bg-info text-white rounded" href="/logout">Logout</a>
                                    </li>
                            </ul>
        
                            
                        </div>
                    </div>
                </nav>
                <% else %>
                <nav class="navbar navbar-expand-md navbar-light bg-blue shadow-sm rounded allign-right">
                    <div class="container">
                        <a class="navbar-brand bg-info text-white rounded" href="/login" >
                            Welcome
                        </a>
        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <!-- Left Side Of Navbar -->
                            
        
                            <!-- Right Side Of Navbar -->
                           
                        </div>
                    </div>
                </nav>
                  <% end %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="recipe_name" style="padding-right: 38px;">Name</label>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preparation %>
    <%= form.text_field :preparation %>
  </div>

  <div class="field">
    <label for="recipe_content" style="padding-right: 26px;">Content</label>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <label for="recipe_prep_time" style="padding-right: 14px;">Prep time</label>
    <%= form.text_field :prep_time %>
  </div>

  <div class="field">
    <label for="recipe_cook_time" style="padding-right: 9px;">Cook time</label>
    <%= form.text_field :cook_time %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_field :ingredients %>
  </div>

  <div class="field" style="display: none;">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, :value => "#{current_user.id}" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Recipes</h1>
<% if @recipes.empty? -%>
  <p>You don't have any recipes.</p>
<% else -%>
  <%= form_tag(recipes_path, method: :get) do %>
  <p>Search for a Recipe </p>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
  <% end %>
  <table>
    <thead>
      <tr>
        <th><%= link_to "Name", :sort => "name"%></th>
        <th><%= link_to "Content", :sort => "content"%> </th>
        <th><%= link_to "Prep time", :sort => "prep_time"%></th>
        <th><%= link_to "Cooking time", :sort => "cook_time"%></th>
        <th>Ingredients</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.name %></td>
          <td><%= recipe.content %></td>
          <td><%= recipe.prep_time %></td>
          <td><%= recipe.cook_time %></td>
          <td><%= recipe.ingredients %></td>
          <td><%= link_to 'Show', recipe %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end -%>

<br>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @recipe.preparation %>
</p>

<p>
  <strong>Desc image:</strong>
  <%= @recipe.desc_image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @recipe.content %>
</p>

<p>
  <strong>Prep time:</strong>
  <%= @recipe.prep_time %>
</p>

<p>
  <strong>Cook time:</strong>
  <%= @recipe.cook_time %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe.user_id %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Recetas</h1>
<p>
  This 
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<% if logged_in?   %>
  <script type="text/javascript">
    window.location.href="/recipes"  
  </script>
<% end %>
<div class="row bg-light">
  <div class="col-md-6 col-md-offset-3 ">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control rounded' %>
    <br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control rounded' %>
    <br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control rounded' %>
    <br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control rounded' %>
    <br>
      <%= f.submit "Create my account", class: "btn btn-primary rounded" %>
    <% end %>
  </div>
</div>